app:
  name: 'Go API Firestore'
  version: '1.0.0'
  is_use_fake_data: true

http:
  gin_mode: debug
  port: '8080'

database:
  pool_max: 2

firestore:
  type: 'service_account'
  project_id: 'xxxx'
  private_key_id: '123asd'
  private_key: '-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n'
  client_email: 'test'
  client_id: 'test'
  auth_uri: 'https://accounts.google.com/o/oauth2/auth'
  token_uri: 'https://oauth2.googleapis.com/token'
  auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs'
  client_x509_cert_url: 'test'
  universe_domain: 'googleapis.com'
